apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-22T13:29:14.145977+05:30"
    description: A Helm chart for Verrazzano
    digest: f48a06ad86d4078d3de7d2698199463a9c394181d31687c701ef27e683934457
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-0.0.54.tgz
    version: 0.0.54
generated: "2020-07-22T13:29:14.131914+05:30"
