apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-22T15:18:17.010369+05:30"
    description: A Helm chart for Verrazzano
    digest: 2f6825a4f2003053c577dac3e5702776ac7af8c11664743811770b730577d1db
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-v0.0.56.tgz
    version: v0.0.56
generated: "2020-07-22T15:18:16.983832+05:30"
