apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-27T10:53:47.138371934Z"
    description: A Helm chart for Verrazzano
    digest: 7be4c424a8b0e62ba70f42edb299ee099d57ed1880c3af2eb7e20ce676129e54
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-v0.0.64.tgz
    version: v0.0.64
generated: "2020-07-27T10:53:47.130696898Z"
