apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-23T12:30:19.608352404Z"
    description: A Helm chart for Verrazzano
    digest: 2fc4284f254bd13d71e9b6c9f350ccd195feec9ebde38feac9ad5180e3ae439f
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-v0.0.67.tgz
    version: v0.0.67
  - apiVersion: v1
    created: "2020-07-23T12:18:00.251313473Z"
    description: A Helm chart for Verrazzano
    digest: 9d0e66e9ed0641ebcaa35bf4e051e47ed0a2d0564778e193510fc4f1e5428e34
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-v0.0.66.tgz
    version: v0.0.66
  - apiVersion: v1
    created: "2020-07-24T10:46:54.499416424Z"
    description: A Helm chart for Verrazzano
    digest: 7033e84d92f91374b0312678a3d52025a54384311a9177f571809692dc9a56ba
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-0.0.63.tgz
    version: 0.0.63
generated: "2020-07-24T10:46:54.492362197Z"
