apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-23T10:37:46.921369699Z"
    description: A Helm chart for Verrazzano
    digest: 763ab29b9c2873624f7d960c50c761d2e2353b540d78cc3caadf62f343a55b8d
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-v0.0.63.tgz
    version: v0.0.63
generated: "2020-07-23T10:37:46.913725046Z"
