apiVersion: v1
entries:
  verrazzano-helm-chart:
  - apiVersion: v1
    created: "2020-07-21T20:15:17.288689+05:30"
    description: A Helm chart for Verrazzano
    digest: 0deacbb7f082201885f0f3f238cc0b9a1674fb657612987c74466797122a6919
    name: verrazzano-helm-chart
    urls:
    - https://github.com/verrazzano/verrazzano-operator/releases/download/verrazzano-0.0.54.tgz
    version: 0.0.54
generated: "2020-07-21T20:15:17.268812+05:30"
