{
 "title": "Coherence Machines Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Machines Summary - Version: $CoherenceVersion</h3></center>"
  },
  {
   "title": "Current Cluster Machines",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_os_available_processors{cluster=~\"$ClusterName\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_swap_space_size{cluster=~\"$ClusterName\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_total_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine) / avg(vendor:coherence_os_total_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine)"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine)",
     "legendFormat": "{{machine}} - Available"
    },
    {
     "expr": "avg(vendor:coherence_os_total_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine)",
     "legendFormat": "{{machine}} - Total"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=~\"$ClusterName\"}[1m])) by (machine)",
     "legendFormat": "{{machine}} - 1 Minute Avg"
    },
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=~\"$ClusterName\"}[5m])) by (machine)",
     "legendFormat": "{{machine}} - 5 Minutes Avg"
    },
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=~\"$ClusterName\"}[15m])) by (machine)",
     "legendFormat": "{{machine}} - 15 Minutes Avg"
    }
   ]
  }
 ]
}