# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoManagedCluster
metadata:
  name: managed-cluster2
  namespace: default
spec:
  description: "My OKE cluster-2"
  type: oke
  serverAddress: https://1.2.3.4:8080
  kubeconfigSecret: managed-cluster2
